package org.example.scheduleservice.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@Data
@Builder
@Schema(description = "Report generated by the optimization algorithm")
public class OptimizationReportDTO {

    @Schema(description = "Total number of slots added")
    private int totalAddedSlots;

    @Schema(description = "Per‑doctor optimization details")
    private List<DoctorOptimizationInfo> doctorsInfo;

    @Data
    @Builder
    @Schema(description = "Optimization info for a single doctor")
    public static class DoctorOptimizationInfo {
        private Long doctorId;
        private String fullName;
        private int existingSlotsBefore;
        private int addedSlots;
        private List<AddedSlotInfo> addedSlotsDetails;
    }

    @Data
    @Builder
    @Schema(description = "Details of an added slot")
    public static class AddedSlotInfo {
        private LocalDate workDate;
        private LocalTime startTime;
        private LocalTime endTime;
    }
}